[project]
name = "vote-sim-results"
version = "0.1.0"
description = "Notebooks and analysis scripts for exploring mcelect simulation output"
requires-python = ">=3.12"
dependencies = [
    "seaborn",
    "pyarrow!=19.0.0",
    "awkward",
    "s3fs",
    "ipyleaflet",
    "tomlkit",
    "pandas",
    "ipykernel",
    "pyyaml",
    "polars>=1.44.2",
    "ruamel-yaml>=0.19.1",
    "panel>=1.9.4",
    "holoviews>=1.23.2",
    "hvplot>=0.12.2",
    "datashader>=0.19.1",
]

[tool.uv]
package = false
